-- Proposta para o schema Pro-Saude. Revisar com o DBA antes de executar.
-- PRSTB027 a PRSTB043 pertencem ao Modulo de Pagamentos. Este script assume
-- que 044 a 049 estao livres; renumerar todos os objetos de forma consistente
-- se houver conflito. PRSTB032 a PRSTB040 continuam sendo a fonte de negocio.

CREATE SEQUENCE PRSSQ045_IA_EXECUCAO START WITH 1 INCREMENT BY 1 CACHE 20;
CREATE SEQUENCE PRSSQ046_IA_TENTATIVA START WITH 1 INCREMENT BY 1 CACHE 20;
CREATE SEQUENCE PRSSQ047_IA_CHAMADA_MODELO START WITH 1 INCREMENT BY 1 CACHE 20;
CREATE SEQUENCE PRSSQ048_IA_ARTEFATO START WITH 1 INCREMENT BY 1 CACHE 20;
CREATE SEQUENCE PRSSQ049_IA_CAMPO_LEITURA START WITH 1 INCREMENT BY 1 CACHE 20;

CREATE TABLE PRSTB044_STATUS_EXECUCAO_IA (
  ID_STATUS_EXECUCAO_IA NUMBER(10) NOT NULL,
  CO_STATUS_EXECUCAO_IA VARCHAR2(20) NOT NULL,
  NO_STATUS_EXECUCAO_IA VARCHAR2(100) NOT NULL,
  IC_TERMINAL CHAR(1) DEFAULT 'N' NOT NULL,
  IC_ATIVO CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_PRSTB044 PRIMARY KEY (ID_STATUS_EXECUCAO_IA),
  CONSTRAINT AK_PRSTB044_01 UNIQUE (CO_STATUS_EXECUCAO_IA),
  CONSTRAINT CC_PRSTB044_01 CHECK (IC_TERMINAL IN ('S','N')),
  CONSTRAINT CC_PRSTB044_02 CHECK (IC_ATIVO IN ('S','N'))
);

CREATE TABLE PRSTB045_IA_EXECUCAO (
  ID_IA_EXECUCAO NUMBER(10) NOT NULL,
  ID_COMPROVANTE_ARQUIVO NUMBER(10) NOT NULL,
  ID_TIPO_DOCUMENTO_COMPROVANTE NUMBER(10) NOT NULL,
  ID_STATUS_EXECUCAO_IA NUMBER(10) NOT NULL,
  NU_EXECUCAO_EXTERNA VARCHAR2(36) NOT NULL,
  NU_SOLICITACAO_EXTERNA VARCHAR2(100) NOT NULL,
  DE_HASH_SHA256 VARCHAR2(64) NOT NULL,
  NO_MODELO VARCHAR2(150),
  NO_VERSAO_SERVICO VARCHAR2(40),
  NO_VERSAO_CONTRATO VARCHAR2(40),
  NO_VERSAO_PROMPT VARCHAR2(40),
  DE_CODIGO_ERRO VARCHAR2(100),
  DE_ERRO VARCHAR2(2000),
  TS_INICIO TIMESTAMP,
  TS_FINALIZACAO TIMESTAMP,
  TS_CRIACAO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_PRSTB045 PRIMARY KEY (ID_IA_EXECUCAO),
  CONSTRAINT AK_PRSTB045_01 UNIQUE (NU_EXECUCAO_EXTERNA),
  CONSTRAINT FK_PRSTB034_PRSTB045 FOREIGN KEY (ID_COMPROVANTE_ARQUIVO) REFERENCES PRSTB034_COMPROVANTE_ARQUIVO (ID_COMPROVANTE_ARQUIVO),
  CONSTRAINT FK_PRSTB029_PRSTB045 FOREIGN KEY (ID_TIPO_DOCUMENTO_COMPROVANTE) REFERENCES PRSTB029_TIPO_DOCUMENTO_COMPROVANTE (ID_TIPO_DOCUMENTO_COMPROVANTE),
  CONSTRAINT FK_PRSTB044_PRSTB045 FOREIGN KEY (ID_STATUS_EXECUCAO_IA) REFERENCES PRSTB044_STATUS_EXECUCAO_IA (ID_STATUS_EXECUCAO_IA)
);
CREATE INDEX IN_PRSTB045_01 ON PRSTB045_IA_EXECUCAO (ID_COMPROVANTE_ARQUIVO, TS_CRIACAO);

CREATE TABLE PRSTB046_IA_TENTATIVA (
  ID_IA_TENTATIVA NUMBER(10) NOT NULL,
  ID_IA_EXECUCAO NUMBER(10) NOT NULL,
  NU_TENTATIVA NUMBER(3) NOT NULL,
  ID_STATUS_EXECUCAO_IA NUMBER(10) NOT NULL,
  NO_IDENTIFICADOR_WORKER VARCHAR2(150),
  DE_CODIGO_ERRO VARCHAR2(100),
  TS_INICIO TIMESTAMP NOT NULL,
  TS_FINALIZACAO TIMESTAMP,
  CONSTRAINT PK_PRSTB046 PRIMARY KEY (ID_IA_TENTATIVA),
  CONSTRAINT AK_PRSTB046_01 UNIQUE (ID_IA_EXECUCAO, NU_TENTATIVA),
  CONSTRAINT FK_PRSTB045_PRSTB046 FOREIGN KEY (ID_IA_EXECUCAO) REFERENCES PRSTB045_IA_EXECUCAO (ID_IA_EXECUCAO),
  CONSTRAINT FK_PRSTB044_PRSTB046 FOREIGN KEY (ID_STATUS_EXECUCAO_IA) REFERENCES PRSTB044_STATUS_EXECUCAO_IA (ID_STATUS_EXECUCAO_IA)
);

CREATE TABLE PRSTB047_IA_CHAMADA_MODELO (
  ID_IA_CHAMADA_MODELO NUMBER(10) NOT NULL,
  ID_IA_TENTATIVA NUMBER(10) NOT NULL,
  NO_MODELO_SOLICITADO VARCHAR2(150) NOT NULL,
  NO_MODELO_EXECUTADO VARCHAR2(150),
  NU_STATUS_HTTP NUMBER(3),
  DE_CODIGO_ERRO VARCHAR2(100),
  NU_TOKENS_ENTRADA NUMBER(12),
  NU_TOKENS_SAIDA NUMBER(12),
  NU_TOKENS_TOTAL NUMBER(12),
  NU_DURACAO_SEGUNDOS NUMBER(12,3),
  TS_INICIO TIMESTAMP NOT NULL,
  TS_FINALIZACAO TIMESTAMP,
  CONSTRAINT PK_PRSTB047 PRIMARY KEY (ID_IA_CHAMADA_MODELO),
  CONSTRAINT FK_PRSTB046_PRSTB047 FOREIGN KEY (ID_IA_TENTATIVA) REFERENCES PRSTB046_IA_TENTATIVA (ID_IA_TENTATIVA)
);

CREATE TABLE PRSTB048_IA_ARTEFATO (
  ID_IA_ARTEFATO NUMBER(10) NOT NULL,
  ID_IA_TENTATIVA NUMBER(10) NOT NULL,
  ID_IA_CHAMADA_MODELO NUMBER(10),
  NO_ARTEFATO VARCHAR2(100) NOT NULL,
  NO_BUCKET VARCHAR2(100) NOT NULL,
  NO_OBJECT_KEY VARCHAR2(500) NOT NULL,
  DE_HASH_SHA256 VARCHAR2(64) NOT NULL,
  NU_TAMANHO_BYTES NUMBER(12) NOT NULL,
  TS_CRIACAO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_PRSTB048 PRIMARY KEY (ID_IA_ARTEFATO),
  CONSTRAINT AK_PRSTB048_01 UNIQUE (ID_IA_TENTATIVA, NO_ARTEFATO, DE_HASH_SHA256),
  CONSTRAINT FK_PRSTB046_PRSTB048 FOREIGN KEY (ID_IA_TENTATIVA) REFERENCES PRSTB046_IA_TENTATIVA (ID_IA_TENTATIVA),
  CONSTRAINT FK_PRSTB047_PRSTB048 FOREIGN KEY (ID_IA_CHAMADA_MODELO) REFERENCES PRSTB047_IA_CHAMADA_MODELO (ID_IA_CHAMADA_MODELO)
);

CREATE TABLE PRSTB049_IA_CAMPO_LEITURA (
  ID_IA_CAMPO_LEITURA NUMBER(10) NOT NULL,
  ID_IA_EXECUCAO NUMBER(10) NOT NULL,
  ID_BENEFICIARIO NUMBER(10),
  ID_COMPROVANTE_CAMPO NUMBER(10),
  CO_CHAVE_CAMPO VARCHAR2(40) NOT NULL,
  DE_VALOR_LIDO VARCHAR2(1000),
  ID_NIVEL_CONFIANCA NUMBER(10) NOT NULL,
  NO_ARQUIVO_ORIGEM VARCHAR2(255),
  DE_EVIDENCIA VARCHAR2(1000),
  NU_PAGINA NUMBER(4),
  TS_CRIACAO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_PRSTB049 PRIMARY KEY (ID_IA_CAMPO_LEITURA),
  CONSTRAINT FK_PRSTB045_PRSTB049 FOREIGN KEY (ID_IA_EXECUCAO) REFERENCES PRSTB045_IA_EXECUCAO (ID_IA_EXECUCAO),
  CONSTRAINT FK_PRSTB014_PRSTB049 FOREIGN KEY (ID_BENEFICIARIO) REFERENCES PRSTB014_BENEFICIARIO (ID_BENEFICIARIO),
  CONSTRAINT FK_PRSTB031_PRSTB049 FOREIGN KEY (ID_NIVEL_CONFIANCA) REFERENCES PRSTB031_NIVEL_CONFIANCA (ID_NIVEL_CONFIANCA),
  CONSTRAINT FK_PRSTB038_PRSTB049 FOREIGN KEY (ID_COMPROVANTE_CAMPO) REFERENCES PRSTB038_COMPROVANTE_CAMPO (ID_COMPROVANTE_CAMPO)
);
CREATE INDEX IN_PRSTB049_01 ON PRSTB049_IA_CAMPO_LEITURA (ID_IA_EXECUCAO, ID_BENEFICIARIO);

INSERT INTO PRSTB044_STATUS_EXECUCAO_IA VALUES (1, 'AGUARDANDO', 'Aguardando processamento', 'N', 'S');
INSERT INTO PRSTB044_STATUS_EXECUCAO_IA VALUES (2, 'PROCESSANDO', 'Em processamento', 'N', 'S');
INSERT INTO PRSTB044_STATUS_EXECUCAO_IA VALUES (3, 'CONCLUIDA', 'Concluida', 'S', 'S');
INSERT INTO PRSTB044_STATUS_EXECUCAO_IA VALUES (4, 'FALHA', 'Falha', 'S', 'S');
COMMIT;
