/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServidorRouteImport } from './routes/servidor'
import { Route as PrimeiroAcessoRouteImport } from './routes/primeiro-acesso'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AssociacaoRouteImport } from './routes/associacao'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServidorMeusDadosRouteImport } from './routes/servidor.meus-dados'
import { Route as ServidorInicioRouteImport } from './routes/servidor.inicio'
import { Route as ServidorDependentesRouteImport } from './routes/servidor.dependentes'
import { Route as ServidorComprovanteRendimentosRouteImport } from './routes/servidor.comprovante-rendimentos'
import { Route as AssociacaoUploadRouteImport } from './routes/associacao.upload'
import { Route as AssociacaoNovaInclusaoRouteImport } from './routes/associacao.nova-inclusao'
import { Route as AdminRequerimentosRouteImport } from './routes/admin.requerimentos'
import { Route as AdminParametrosRouteImport } from './routes/admin.parametros'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminComprovantesRouteImport } from './routes/admin.comprovantes'
import { Route as AdminCargaInicialRouteImport } from './routes/admin.carga-inicial'
import { Route as ServidorPagamentosIndexRouteImport } from './routes/servidor.pagamentos.index'
import { Route as AssociacaoGerenciamentoIndexRouteImport } from './routes/associacao.gerenciamento.index'
import { Route as AdminServidoresIndexRouteImport } from './routes/admin.servidores.index'
import { Route as AdminRelatoriosIndexRouteImport } from './routes/admin.relatorios.index'
import { Route as ServidorRequerimentoNovoPlanoRouteImport } from './routes/servidor.requerimento.novo-plano'
import { Route as ServidorRequerimentoNovoRouteImport } from './routes/servidor.requerimento.novo'
import { Route as ServidorRequerimentoIncluirDependenteRouteImport } from './routes/servidor.requerimento.incluir-dependente'
import { Route as ServidorRequerimentoExclusaoRouteImport } from './routes/servidor.requerimento.exclusao'
import { Route as ServidorPagamentosEnviarRouteImport } from './routes/servidor.pagamentos.enviar'
import { Route as AssociacaoGerenciamentoIdRouteImport } from './routes/associacao.gerenciamento.$id'
import { Route as AdminServidoresIdRouteImport } from './routes/admin.servidores.$id'
import { Route as AdminRelatoriosPagamentosRouteImport } from './routes/admin.relatorios.pagamentos'
import { Route as AdminRelatoriosGerencialRouteImport } from './routes/admin.relatorios.gerencial'
import { Route as AdminRelatoriosDocumentacaoRouteImport } from './routes/admin.relatorios.documentacao'
import { Route as AdminRelatoriosExtratoIndexRouteImport } from './routes/admin.relatorios.extrato.index'
import { Route as AdminRelatoriosExtratoMatriculaRouteImport } from './routes/admin.relatorios.extrato.$matricula'

const ServidorRoute = ServidorRouteImport.update({
  id: '/servidor',
  path: '/servidor',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiroAcessoRoute = PrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociacaoRoute = AssociacaoRouteImport.update({
  id: '/associacao',
  path: '/associacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServidorMeusDadosRoute = ServidorMeusDadosRouteImport.update({
  id: '/meus-dados',
  path: '/meus-dados',
  getParentRoute: () => ServidorRoute,
} as any)
const ServidorInicioRoute = ServidorInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => ServidorRoute,
} as any)
const ServidorDependentesRoute = ServidorDependentesRouteImport.update({
  id: '/dependentes',
  path: '/dependentes',
  getParentRoute: () => ServidorRoute,
} as any)
const ServidorComprovanteRendimentosRoute =
  ServidorComprovanteRendimentosRouteImport.update({
    id: '/comprovante-rendimentos',
    path: '/comprovante-rendimentos',
    getParentRoute: () => ServidorRoute,
  } as any)
const AssociacaoUploadRoute = AssociacaoUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AssociacaoRoute,
} as any)
const AssociacaoNovaInclusaoRoute = AssociacaoNovaInclusaoRouteImport.update({
  id: '/nova-inclusao',
  path: '/nova-inclusao',
  getParentRoute: () => AssociacaoRoute,
} as any)
const AdminRequerimentosRoute = AdminRequerimentosRouteImport.update({
  id: '/requerimentos',
  path: '/requerimentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametrosRoute = AdminParametrosRouteImport.update({
  id: '/parametros',
  path: '/parametros',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComprovantesRoute = AdminComprovantesRouteImport.update({
  id: '/comprovantes',
  path: '/comprovantes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCargaInicialRoute = AdminCargaInicialRouteImport.update({
  id: '/carga-inicial',
  path: '/carga-inicial',
  getParentRoute: () => AdminRoute,
} as any)
const ServidorPagamentosIndexRoute = ServidorPagamentosIndexRouteImport.update({
  id: '/pagamentos/',
  path: '/pagamentos/',
  getParentRoute: () => ServidorRoute,
} as any)
const AssociacaoGerenciamentoIndexRoute =
  AssociacaoGerenciamentoIndexRouteImport.update({
    id: '/gerenciamento/',
    path: '/gerenciamento/',
    getParentRoute: () => AssociacaoRoute,
  } as any)
const AdminServidoresIndexRoute = AdminServidoresIndexRouteImport.update({
  id: '/servidores/',
  path: '/servidores/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosIndexRoute = AdminRelatoriosIndexRouteImport.update({
  id: '/relatorios/',
  path: '/relatorios/',
  getParentRoute: () => AdminRoute,
} as any)
const ServidorRequerimentoNovoPlanoRoute =
  ServidorRequerimentoNovoPlanoRouteImport.update({
    id: '/requerimento/novo-plano',
    path: '/requerimento/novo-plano',
    getParentRoute: () => ServidorRoute,
  } as any)
const ServidorRequerimentoNovoRoute =
  ServidorRequerimentoNovoRouteImport.update({
    id: '/requerimento/novo',
    path: '/requerimento/novo',
    getParentRoute: () => ServidorRoute,
  } as any)
const ServidorRequerimentoIncluirDependenteRoute =
  ServidorRequerimentoIncluirDependenteRouteImport.update({
    id: '/requerimento/incluir-dependente',
    path: '/requerimento/incluir-dependente',
    getParentRoute: () => ServidorRoute,
  } as any)
const ServidorRequerimentoExclusaoRoute =
  ServidorRequerimentoExclusaoRouteImport.update({
    id: '/requerimento/exclusao',
    path: '/requerimento/exclusao',
    getParentRoute: () => ServidorRoute,
  } as any)
const ServidorPagamentosEnviarRoute =
  ServidorPagamentosEnviarRouteImport.update({
    id: '/pagamentos/enviar',
    path: '/pagamentos/enviar',
    getParentRoute: () => ServidorRoute,
  } as any)
const AssociacaoGerenciamentoIdRoute =
  AssociacaoGerenciamentoIdRouteImport.update({
    id: '/gerenciamento/$id',
    path: '/gerenciamento/$id',
    getParentRoute: () => AssociacaoRoute,
  } as any)
const AdminServidoresIdRoute = AdminServidoresIdRouteImport.update({
  id: '/servidores/$id',
  path: '/servidores/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosPagamentosRoute =
  AdminRelatoriosPagamentosRouteImport.update({
    id: '/relatorios/pagamentos',
    path: '/relatorios/pagamentos',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminRelatoriosGerencialRoute =
  AdminRelatoriosGerencialRouteImport.update({
    id: '/relatorios/gerencial',
    path: '/relatorios/gerencial',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminRelatoriosDocumentacaoRoute =
  AdminRelatoriosDocumentacaoRouteImport.update({
    id: '/relatorios/documentacao',
    path: '/relatorios/documentacao',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminRelatoriosExtratoIndexRoute =
  AdminRelatoriosExtratoIndexRouteImport.update({
    id: '/relatorios/extrato/',
    path: '/relatorios/extrato/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminRelatoriosExtratoMatriculaRoute =
  AdminRelatoriosExtratoMatriculaRouteImport.update({
    id: '/relatorios/extrato/$matricula',
    path: '/relatorios/extrato/$matricula',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/associacao': typeof AssociacaoRouteWithChildren
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/servidor': typeof ServidorRouteWithChildren
  '/admin/carga-inicial': typeof AdminCargaInicialRoute
  '/admin/comprovantes': typeof AdminComprovantesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/parametros': typeof AdminParametrosRoute
  '/admin/requerimentos': typeof AdminRequerimentosRoute
  '/associacao/nova-inclusao': typeof AssociacaoNovaInclusaoRoute
  '/associacao/upload': typeof AssociacaoUploadRoute
  '/servidor/comprovante-rendimentos': typeof ServidorComprovanteRendimentosRoute
  '/servidor/dependentes': typeof ServidorDependentesRoute
  '/servidor/inicio': typeof ServidorInicioRoute
  '/servidor/meus-dados': typeof ServidorMeusDadosRoute
  '/admin/relatorios/documentacao': typeof AdminRelatoriosDocumentacaoRoute
  '/admin/relatorios/gerencial': typeof AdminRelatoriosGerencialRoute
  '/admin/relatorios/pagamentos': typeof AdminRelatoriosPagamentosRoute
  '/admin/servidores/$id': typeof AdminServidoresIdRoute
  '/associacao/gerenciamento/$id': typeof AssociacaoGerenciamentoIdRoute
  '/servidor/pagamentos/enviar': typeof ServidorPagamentosEnviarRoute
  '/servidor/requerimento/exclusao': typeof ServidorRequerimentoExclusaoRoute
  '/servidor/requerimento/incluir-dependente': typeof ServidorRequerimentoIncluirDependenteRoute
  '/servidor/requerimento/novo': typeof ServidorRequerimentoNovoRoute
  '/servidor/requerimento/novo-plano': typeof ServidorRequerimentoNovoPlanoRoute
  '/admin/relatorios/': typeof AdminRelatoriosIndexRoute
  '/admin/servidores/': typeof AdminServidoresIndexRoute
  '/associacao/gerenciamento/': typeof AssociacaoGerenciamentoIndexRoute
  '/servidor/pagamentos/': typeof ServidorPagamentosIndexRoute
  '/admin/relatorios/extrato/$matricula': typeof AdminRelatoriosExtratoMatriculaRoute
  '/admin/relatorios/extrato/': typeof AdminRelatoriosExtratoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/associacao': typeof AssociacaoRouteWithChildren
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/servidor': typeof ServidorRouteWithChildren
  '/admin/carga-inicial': typeof AdminCargaInicialRoute
  '/admin/comprovantes': typeof AdminComprovantesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/parametros': typeof AdminParametrosRoute
  '/admin/requerimentos': typeof AdminRequerimentosRoute
  '/associacao/nova-inclusao': typeof AssociacaoNovaInclusaoRoute
  '/associacao/upload': typeof AssociacaoUploadRoute
  '/servidor/comprovante-rendimentos': typeof ServidorComprovanteRendimentosRoute
  '/servidor/dependentes': typeof ServidorDependentesRoute
  '/servidor/inicio': typeof ServidorInicioRoute
  '/servidor/meus-dados': typeof ServidorMeusDadosRoute
  '/admin/relatorios/documentacao': typeof AdminRelatoriosDocumentacaoRoute
  '/admin/relatorios/gerencial': typeof AdminRelatoriosGerencialRoute
  '/admin/relatorios/pagamentos': typeof AdminRelatoriosPagamentosRoute
  '/admin/servidores/$id': typeof AdminServidoresIdRoute
  '/associacao/gerenciamento/$id': typeof AssociacaoGerenciamentoIdRoute
  '/servidor/pagamentos/enviar': typeof ServidorPagamentosEnviarRoute
  '/servidor/requerimento/exclusao': typeof ServidorRequerimentoExclusaoRoute
  '/servidor/requerimento/incluir-dependente': typeof ServidorRequerimentoIncluirDependenteRoute
  '/servidor/requerimento/novo': typeof ServidorRequerimentoNovoRoute
  '/servidor/requerimento/novo-plano': typeof ServidorRequerimentoNovoPlanoRoute
  '/admin/relatorios': typeof AdminRelatoriosIndexRoute
  '/admin/servidores': typeof AdminServidoresIndexRoute
  '/associacao/gerenciamento': typeof AssociacaoGerenciamentoIndexRoute
  '/servidor/pagamentos': typeof ServidorPagamentosIndexRoute
  '/admin/relatorios/extrato/$matricula': typeof AdminRelatoriosExtratoMatriculaRoute
  '/admin/relatorios/extrato': typeof AdminRelatoriosExtratoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/associacao': typeof AssociacaoRouteWithChildren
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/servidor': typeof ServidorRouteWithChildren
  '/admin/carga-inicial': typeof AdminCargaInicialRoute
  '/admin/comprovantes': typeof AdminComprovantesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/parametros': typeof AdminParametrosRoute
  '/admin/requerimentos': typeof AdminRequerimentosRoute
  '/associacao/nova-inclusao': typeof AssociacaoNovaInclusaoRoute
  '/associacao/upload': typeof AssociacaoUploadRoute
  '/servidor/comprovante-rendimentos': typeof ServidorComprovanteRendimentosRoute
  '/servidor/dependentes': typeof ServidorDependentesRoute
  '/servidor/inicio': typeof ServidorInicioRoute
  '/servidor/meus-dados': typeof ServidorMeusDadosRoute
  '/admin/relatorios/documentacao': typeof AdminRelatoriosDocumentacaoRoute
  '/admin/relatorios/gerencial': typeof AdminRelatoriosGerencialRoute
  '/admin/relatorios/pagamentos': typeof AdminRelatoriosPagamentosRoute
  '/admin/servidores/$id': typeof AdminServidoresIdRoute
  '/associacao/gerenciamento/$id': typeof AssociacaoGerenciamentoIdRoute
  '/servidor/pagamentos/enviar': typeof ServidorPagamentosEnviarRoute
  '/servidor/requerimento/exclusao': typeof ServidorRequerimentoExclusaoRoute
  '/servidor/requerimento/incluir-dependente': typeof ServidorRequerimentoIncluirDependenteRoute
  '/servidor/requerimento/novo': typeof ServidorRequerimentoNovoRoute
  '/servidor/requerimento/novo-plano': typeof ServidorRequerimentoNovoPlanoRoute
  '/admin/relatorios/': typeof AdminRelatoriosIndexRoute
  '/admin/servidores/': typeof AdminServidoresIndexRoute
  '/associacao/gerenciamento/': typeof AssociacaoGerenciamentoIndexRoute
  '/servidor/pagamentos/': typeof ServidorPagamentosIndexRoute
  '/admin/relatorios/extrato/$matricula': typeof AdminRelatoriosExtratoMatriculaRoute
  '/admin/relatorios/extrato/': typeof AdminRelatoriosExtratoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/associacao'
    | '/login'
    | '/primeiro-acesso'
    | '/servidor'
    | '/admin/carga-inicial'
    | '/admin/comprovantes'
    | '/admin/dashboard'
    | '/admin/parametros'
    | '/admin/requerimentos'
    | '/associacao/nova-inclusao'
    | '/associacao/upload'
    | '/servidor/comprovante-rendimentos'
    | '/servidor/dependentes'
    | '/servidor/inicio'
    | '/servidor/meus-dados'
    | '/admin/relatorios/documentacao'
    | '/admin/relatorios/gerencial'
    | '/admin/relatorios/pagamentos'
    | '/admin/servidores/$id'
    | '/associacao/gerenciamento/$id'
    | '/servidor/pagamentos/enviar'
    | '/servidor/requerimento/exclusao'
    | '/servidor/requerimento/incluir-dependente'
    | '/servidor/requerimento/novo'
    | '/servidor/requerimento/novo-plano'
    | '/admin/relatorios/'
    | '/admin/servidores/'
    | '/associacao/gerenciamento/'
    | '/servidor/pagamentos/'
    | '/admin/relatorios/extrato/$matricula'
    | '/admin/relatorios/extrato/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/associacao'
    | '/login'
    | '/primeiro-acesso'
    | '/servidor'
    | '/admin/carga-inicial'
    | '/admin/comprovantes'
    | '/admin/dashboard'
    | '/admin/parametros'
    | '/admin/requerimentos'
    | '/associacao/nova-inclusao'
    | '/associacao/upload'
    | '/servidor/comprovante-rendimentos'
    | '/servidor/dependentes'
    | '/servidor/inicio'
    | '/servidor/meus-dados'
    | '/admin/relatorios/documentacao'
    | '/admin/relatorios/gerencial'
    | '/admin/relatorios/pagamentos'
    | '/admin/servidores/$id'
    | '/associacao/gerenciamento/$id'
    | '/servidor/pagamentos/enviar'
    | '/servidor/requerimento/exclusao'
    | '/servidor/requerimento/incluir-dependente'
    | '/servidor/requerimento/novo'
    | '/servidor/requerimento/novo-plano'
    | '/admin/relatorios'
    | '/admin/servidores'
    | '/associacao/gerenciamento'
    | '/servidor/pagamentos'
    | '/admin/relatorios/extrato/$matricula'
    | '/admin/relatorios/extrato'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/associacao'
    | '/login'
    | '/primeiro-acesso'
    | '/servidor'
    | '/admin/carga-inicial'
    | '/admin/comprovantes'
    | '/admin/dashboard'
    | '/admin/parametros'
    | '/admin/requerimentos'
    | '/associacao/nova-inclusao'
    | '/associacao/upload'
    | '/servidor/comprovante-rendimentos'
    | '/servidor/dependentes'
    | '/servidor/inicio'
    | '/servidor/meus-dados'
    | '/admin/relatorios/documentacao'
    | '/admin/relatorios/gerencial'
    | '/admin/relatorios/pagamentos'
    | '/admin/servidores/$id'
    | '/associacao/gerenciamento/$id'
    | '/servidor/pagamentos/enviar'
    | '/servidor/requerimento/exclusao'
    | '/servidor/requerimento/incluir-dependente'
    | '/servidor/requerimento/novo'
    | '/servidor/requerimento/novo-plano'
    | '/admin/relatorios/'
    | '/admin/servidores/'
    | '/associacao/gerenciamento/'
    | '/servidor/pagamentos/'
    | '/admin/relatorios/extrato/$matricula'
    | '/admin/relatorios/extrato/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssociacaoRoute: typeof AssociacaoRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrimeiroAcessoRoute: typeof PrimeiroAcessoRoute
  ServidorRoute: typeof ServidorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servidor': {
      id: '/servidor'
      path: '/servidor'
      fullPath: '/servidor'
      preLoaderRoute: typeof ServidorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiro-acesso': {
      id: '/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof PrimeiroAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/associacao': {
      id: '/associacao'
      path: '/associacao'
      fullPath: '/associacao'
      preLoaderRoute: typeof AssociacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servidor/meus-dados': {
      id: '/servidor/meus-dados'
      path: '/meus-dados'
      fullPath: '/servidor/meus-dados'
      preLoaderRoute: typeof ServidorMeusDadosRouteImport
      parentRoute: typeof ServidorRoute
    }
    '/servidor/inicio': {
      id: '/servidor/inicio'
      path: '/inicio'
      fullPath: '/servidor/inicio'
      preLoaderRoute: typeof ServidorInicioRouteImport
      parentRoute: typeof ServidorRoute
    }
    '/servidor/dependentes': {
      id: '/servidor/dependentes'
      path: '/dependentes'
      fullPath: '/servidor/dependentes'
      preLoaderRoute: typeof ServidorDependentesRouteImport
      parentRoute: typeof ServidorRoute
    }
    '/servidor/comprovante-rendimentos': {
      id: '/servidor/comprovante-rendimentos'
      path: '/comprovante-rendimentos'
      fullPath: '/servidor/comprovante-rendimentos'
      preLoaderRoute: typeof ServidorComprovanteRendimentosRouteImport
      parentRoute: typeof ServidorRoute
    }
    '/associacao/upload': {
      id: '/associacao/upload'
      path: '/upload'
      fullPath: '/associacao/upload'
      preLoaderRoute: typeof AssociacaoUploadRouteImport
      parentRoute: typeof AssociacaoRoute
    }
    '/associacao/nova-inclusao': {
      id: '/associacao/nova-inclusao'
      path: '/nova-inclusao'
      fullPath: '/associacao/nova-inclusao'
      preLoaderRoute: typeof AssociacaoNovaInclusaoRouteImport
      parentRoute: typeof AssociacaoRoute
    }
    '/admin/requerimentos': {
      id: '/admin/requerimentos'
      path: '/requerimentos'
      fullPath: '/admin/requerimentos'
      preLoaderRoute: typeof AdminRequerimentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametros': {
      id: '/admin/parametros'
      path: '/parametros'
      fullPath: '/admin/parametros'
      preLoaderRoute: typeof AdminParametrosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comprovantes': {
      id: '/admin/comprovantes'
      path: '/comprovantes'
      fullPath: '/admin/comprovantes'
      preLoaderRoute: typeof AdminComprovantesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carga-inicial': {
      id: '/admin/carga-inicial'
      path: '/carga-inicial'
      fullPath: '/admin/carga-inicial'
      preLoaderRoute: typeof AdminCargaInicialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/servidor/pagamentos/': {
      id: '/servidor/pagamentos/'
      path: '/pagamentos'
      fullPath: '/servidor/pagamentos/'
      preLoaderRoute: typeof ServidorPagamentosIndexRouteImport
      parentRoute: typeof ServidorRoute
    }
    '/associacao/gerenciamento/': {
      id: '/associacao/gerenciamento/'
      path: '/gerenciamento'
      fullPath: '/associacao/gerenciamento/'
      preLoaderRoute: typeof AssociacaoGerenciamentoIndexRouteImport
      parentRoute: typeof AssociacaoRoute
    }
    '/admin/servidores/': {
      id: '/admin/servidores/'
      path: '/servidores'
      fullPath: '/admin/servidores/'
      preLoaderRoute: typeof AdminServidoresIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios/': {
      id: '/admin/relatorios/'
      path: '/relatorios'
      fullPath: '/admin/relatorios/'
      preLoaderRoute: typeof AdminRelatoriosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/servidor/requerimento/novo-plano': {
      id: '/servidor/requerimento/novo-plano'
      path: '/requerimento/novo-plano'
      fullPath: '/servidor/requerimento/novo-plano'
      preLoaderRoute: typeof ServidorRequerimentoNovoPlanoRouteImport
      parentRoute: typeof ServidorRoute
    }
    '/servidor/requerimento/novo': {
      id: '/servidor/requerimento/novo'
      path: '/requerimento/novo'
      fullPath: '/servidor/requerimento/novo'
      preLoaderRoute: typeof ServidorRequerimentoNovoRouteImport
      parentRoute: typeof ServidorRoute
    }
    '/servidor/requerimento/incluir-dependente': {
      id: '/servidor/requerimento/incluir-dependente'
      path: '/requerimento/incluir-dependente'
      fullPath: '/servidor/requerimento/incluir-dependente'
      preLoaderRoute: typeof ServidorRequerimentoIncluirDependenteRouteImport
      parentRoute: typeof ServidorRoute
    }
    '/servidor/requerimento/exclusao': {
      id: '/servidor/requerimento/exclusao'
      path: '/requerimento/exclusao'
      fullPath: '/servidor/requerimento/exclusao'
      preLoaderRoute: typeof ServidorRequerimentoExclusaoRouteImport
      parentRoute: typeof ServidorRoute
    }
    '/servidor/pagamentos/enviar': {
      id: '/servidor/pagamentos/enviar'
      path: '/pagamentos/enviar'
      fullPath: '/servidor/pagamentos/enviar'
      preLoaderRoute: typeof ServidorPagamentosEnviarRouteImport
      parentRoute: typeof ServidorRoute
    }
    '/associacao/gerenciamento/$id': {
      id: '/associacao/gerenciamento/$id'
      path: '/gerenciamento/$id'
      fullPath: '/associacao/gerenciamento/$id'
      preLoaderRoute: typeof AssociacaoGerenciamentoIdRouteImport
      parentRoute: typeof AssociacaoRoute
    }
    '/admin/servidores/$id': {
      id: '/admin/servidores/$id'
      path: '/servidores/$id'
      fullPath: '/admin/servidores/$id'
      preLoaderRoute: typeof AdminServidoresIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios/pagamentos': {
      id: '/admin/relatorios/pagamentos'
      path: '/relatorios/pagamentos'
      fullPath: '/admin/relatorios/pagamentos'
      preLoaderRoute: typeof AdminRelatoriosPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios/gerencial': {
      id: '/admin/relatorios/gerencial'
      path: '/relatorios/gerencial'
      fullPath: '/admin/relatorios/gerencial'
      preLoaderRoute: typeof AdminRelatoriosGerencialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios/documentacao': {
      id: '/admin/relatorios/documentacao'
      path: '/relatorios/documentacao'
      fullPath: '/admin/relatorios/documentacao'
      preLoaderRoute: typeof AdminRelatoriosDocumentacaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios/extrato/': {
      id: '/admin/relatorios/extrato/'
      path: '/relatorios/extrato'
      fullPath: '/admin/relatorios/extrato/'
      preLoaderRoute: typeof AdminRelatoriosExtratoIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios/extrato/$matricula': {
      id: '/admin/relatorios/extrato/$matricula'
      path: '/relatorios/extrato/$matricula'
      fullPath: '/admin/relatorios/extrato/$matricula'
      preLoaderRoute: typeof AdminRelatoriosExtratoMatriculaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCargaInicialRoute: typeof AdminCargaInicialRoute
  AdminComprovantesRoute: typeof AdminComprovantesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminParametrosRoute: typeof AdminParametrosRoute
  AdminRequerimentosRoute: typeof AdminRequerimentosRoute
  AdminRelatoriosDocumentacaoRoute: typeof AdminRelatoriosDocumentacaoRoute
  AdminRelatoriosGerencialRoute: typeof AdminRelatoriosGerencialRoute
  AdminRelatoriosPagamentosRoute: typeof AdminRelatoriosPagamentosRoute
  AdminServidoresIdRoute: typeof AdminServidoresIdRoute
  AdminRelatoriosIndexRoute: typeof AdminRelatoriosIndexRoute
  AdminServidoresIndexRoute: typeof AdminServidoresIndexRoute
  AdminRelatoriosExtratoMatriculaRoute: typeof AdminRelatoriosExtratoMatriculaRoute
  AdminRelatoriosExtratoIndexRoute: typeof AdminRelatoriosExtratoIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCargaInicialRoute: AdminCargaInicialRoute,
  AdminComprovantesRoute: AdminComprovantesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminParametrosRoute: AdminParametrosRoute,
  AdminRequerimentosRoute: AdminRequerimentosRoute,
  AdminRelatoriosDocumentacaoRoute: AdminRelatoriosDocumentacaoRoute,
  AdminRelatoriosGerencialRoute: AdminRelatoriosGerencialRoute,
  AdminRelatoriosPagamentosRoute: AdminRelatoriosPagamentosRoute,
  AdminServidoresIdRoute: AdminServidoresIdRoute,
  AdminRelatoriosIndexRoute: AdminRelatoriosIndexRoute,
  AdminServidoresIndexRoute: AdminServidoresIndexRoute,
  AdminRelatoriosExtratoMatriculaRoute: AdminRelatoriosExtratoMatriculaRoute,
  AdminRelatoriosExtratoIndexRoute: AdminRelatoriosExtratoIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AssociacaoRouteChildren {
  AssociacaoNovaInclusaoRoute: typeof AssociacaoNovaInclusaoRoute
  AssociacaoUploadRoute: typeof AssociacaoUploadRoute
  AssociacaoGerenciamentoIdRoute: typeof AssociacaoGerenciamentoIdRoute
  AssociacaoGerenciamentoIndexRoute: typeof AssociacaoGerenciamentoIndexRoute
}

const AssociacaoRouteChildren: AssociacaoRouteChildren = {
  AssociacaoNovaInclusaoRoute: AssociacaoNovaInclusaoRoute,
  AssociacaoUploadRoute: AssociacaoUploadRoute,
  AssociacaoGerenciamentoIdRoute: AssociacaoGerenciamentoIdRoute,
  AssociacaoGerenciamentoIndexRoute: AssociacaoGerenciamentoIndexRoute,
}

const AssociacaoRouteWithChildren = AssociacaoRoute._addFileChildren(
  AssociacaoRouteChildren,
)

interface ServidorRouteChildren {
  ServidorComprovanteRendimentosRoute: typeof ServidorComprovanteRendimentosRoute
  ServidorDependentesRoute: typeof ServidorDependentesRoute
  ServidorInicioRoute: typeof ServidorInicioRoute
  ServidorMeusDadosRoute: typeof ServidorMeusDadosRoute
  ServidorPagamentosEnviarRoute: typeof ServidorPagamentosEnviarRoute
  ServidorRequerimentoExclusaoRoute: typeof ServidorRequerimentoExclusaoRoute
  ServidorRequerimentoIncluirDependenteRoute: typeof ServidorRequerimentoIncluirDependenteRoute
  ServidorRequerimentoNovoRoute: typeof ServidorRequerimentoNovoRoute
  ServidorRequerimentoNovoPlanoRoute: typeof ServidorRequerimentoNovoPlanoRoute
  ServidorPagamentosIndexRoute: typeof ServidorPagamentosIndexRoute
}

const ServidorRouteChildren: ServidorRouteChildren = {
  ServidorComprovanteRendimentosRoute: ServidorComprovanteRendimentosRoute,
  ServidorDependentesRoute: ServidorDependentesRoute,
  ServidorInicioRoute: ServidorInicioRoute,
  ServidorMeusDadosRoute: ServidorMeusDadosRoute,
  ServidorPagamentosEnviarRoute: ServidorPagamentosEnviarRoute,
  ServidorRequerimentoExclusaoRoute: ServidorRequerimentoExclusaoRoute,
  ServidorRequerimentoIncluirDependenteRoute:
    ServidorRequerimentoIncluirDependenteRoute,
  ServidorRequerimentoNovoRoute: ServidorRequerimentoNovoRoute,
  ServidorRequerimentoNovoPlanoRoute: ServidorRequerimentoNovoPlanoRoute,
  ServidorPagamentosIndexRoute: ServidorPagamentosIndexRoute,
}

const ServidorRouteWithChildren = ServidorRoute._addFileChildren(
  ServidorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AssociacaoRoute: AssociacaoRouteWithChildren,
  LoginRoute: LoginRoute,
  PrimeiroAcessoRoute: PrimeiroAcessoRoute,
  ServidorRoute: ServidorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
